version: "3"

tasks:
    lint:
        description: Lint the code
        dir: "{{.USER_WORKING_DIR}}"
        cmds:
            - uv run ruff format ./slang ./tests
            - uv run ruff check ./slang ./tests  --fix
            - uv run pyright ./slang ./tests
    test:
        description: Run tests
        dir: "{{.USER_WORKING_DIR}}"
        cmds:
            - uv run pytest --maxfail=1 --tb=long
