"""
Example usage of the Slang internationalization library.

This example demonstrates how to use type-safe translations generated by Slang.
Run `slang generate` first to create the translation files.
"""

from .__tr__.translations import get_translations, Languages


def demo_basic_usage():
    """Demonstrate basic translation usage."""
    print("🌍 Basic Translation Usage")
    print("=" * 40)

    # Get English translations
    t_en = get_translations(Languages.EN)
    print(f"English: {t_en.welcome.title}")
    print(f"English: {t_en.app.name} - {t_en.app.tagline}")

    # Get Spanish translations
    t_es = get_translations(Languages.ES)
    print(f"Spanish: {t_es.welcome.title}")
    print(f"Spanish: {t_es.app.name} - {t_es.app.tagline}")

    # Get French translations
    t_fr = get_translations(Languages.FR)
    print(f"French: {t_fr.welcome.title}")
    print(f"French: {t_fr.app.name} - {t_fr.app.tagline}")
    print()


def demo_parameterized_translations():
    """Demonstrate parameterized translations with type safety."""
    print("🔧 Parameterized Translations")
    print("=" * 40)

    # Auto-detected parameters (using {placeholder} syntax)
    t_en = get_translations(Languages.EN)
    t_es = get_translations(Languages.ES)
    t_fr = get_translations(Languages.FR)

    name = "Alice"
    print(f"English: {t_en.greetings.hello(name=name)}")
    print(f"Spanish: {t_es.greetings.hello(name=name)}")
    print(f"French: {t_fr.greetings.hello(name=name)}")
    print()

    # Explicit parameters with type annotations
    message_count = 5
    print(f"English: {t_en.messages.count(count=message_count)}")
    print(f"Spanish: {t_es.messages.count(count=message_count)}")
    print(f"French: {t_fr.messages.count(count=message_count)}")
    print()

    # Complex parameters
    unread_count = 3
    print(f"English: {t_en.messages.unread(unread=unread_count)}")
    print(f"Spanish: {t_es.messages.unread(unread=unread_count)}")
    print(f"French: {t_fr.messages.unread(unread=unread_count)}")
    print()


def demo_nested_namespaces():
    """Demonstrate nested namespace access."""
    print("📁 Nested Namespaces")
    print("=" * 40)

    t_en = get_translations(Languages.EN)
    t_es = get_translations(Languages.ES)
    t_fr = get_translations(Languages.FR)

    # User profile section
    print("User Profile:")
    print(f"  English: {t_en.user.profile.title} -> {t_en.user.profile.edit}")
    print(f"  Spanish: {t_es.user.profile.title} -> {t_es.user.profile.edit}")
    print(f"  French: {t_fr.user.profile.title} -> {t_fr.user.profile.edit}")
    print()

    # Navigation section
    print("Navigation:")
    print(
        f"  English: {t_en.navigation.home} | {t_en.navigation.about} | {t_en.navigation.settings}"
    )
    print(
        f"  Spanish: {t_es.navigation.home} | {t_es.navigation.about} | {t_es.navigation.settings}"
    )
    print(
        f"  French: {t_fr.navigation.home} | {t_fr.navigation.about} | {t_fr.navigation.settings}"
    )
    print()


def demo_error_messages():
    """Demonstrate error message translations."""
    print("❌ Error Messages")
    print("=" * 40)

    t_en = get_translations(Languages.EN)
    t_es = get_translations(Languages.ES)
    t_fr = get_translations(Languages.FR)

    errors = ["not_found", "unauthorized", "server_error", "network_error"]

    for error in errors:
        print(f"{error}:")
        print(f"  EN: {getattr(t_en.errors, error)}")
        print(f"  ES: {getattr(t_es.errors, error)}")
        print(f"  FR: {getattr(t_fr.errors, error)}")
        print()


def demo_dynamic_language_selection():
    """Demonstrate dynamic language selection."""
    print("🌐 Dynamic Language Selection")
    print("=" * 40)

    # Simulate user language preferences
    user_languages = ["en", "es", "fr"]

    for lang_code in user_languages:
        # Convert string to enum
        try:
            language = Languages(lang_code)
            t = get_translations(language)

            print(f"Language: {lang_code.upper()}")
            print(f"  Welcome: {t.welcome.message}")
            print(f"  Status: {t.status.online}")
            print()

        except ValueError:
            print(f"Unsupported language: {lang_code}")


def demo_notifications():
    """Demonstrate notification translations with parameters."""
    print("🔔 Notification Examples")
    print("=" * 40)

    t_en = get_translations(Languages.EN)
    t_es = get_translations(Languages.ES)
    t_fr = get_translations(Languages.FR)

    # Notification with sender parameter
    sender = "Bob"
    print("New message notification:")
    print(f"  EN: {t_en.notifications.new_message(sender=sender)}")
    print(f"  ES: {t_es.notifications.new_message(sender=sender)}")
    print(f"  FR: {t_fr.notifications.new_message(sender=sender)}")
    print()

    # Friend request notification
    user = "Charlie"
    print("Friend request notification:")
    print(f"  EN: {t_en.notifications.friend_request(user=user)}")
    print(f"  ES: {t_es.notifications.friend_request(user=user)}")
    print(f"  FR: {t_fr.notifications.friend_request(user=user)}")
    print()

    # System update notification
    minutes = 10
    print("System update notification:")
    print(f"  EN: {t_en.notifications.system_update(minutes=minutes)}")
    print(f"  ES: {t_es.notifications.system_update(minutes=minutes)}")
    print(f"  FR: {t_fr.notifications.system_update(minutes=minutes)}")
    print()


def demo_type_safety():
    """Demonstrate type safety features."""
    print("🛡️  Type Safety Demonstration")
    print("=" * 40)

    t = get_translations(Languages.EN)

    # This works - correct usage
    print("✅ Correct usage:")
    print(f"  {t.messages.count(count=5)}")
    print(f"  {t.greetings.hello(name='Alice')}")
    print()

    # These would cause type errors in a type checker:
    print("❌ These would be caught by type checkers:")
    print("  # t.messages.count(count='invalid')  # Wrong type")
    print("  # t.nonexistent.field  # Field doesn't exist")
    print("  # t.greetings.hello()  # Missing required parameter")
    print()


def main():
    """Main demonstration function."""
    print("🌍 Slang Translation Library Example")
    print("=====================================")
    print()
    print("This example demonstrates type-safe internationalization")
    print("with automatically generated translation classes.")
    print()

    demo_basic_usage()
    demo_parameterized_translations()
    demo_nested_namespaces()
    demo_error_messages()
    demo_dynamic_language_selection()
    demo_notifications()
    demo_type_safety()

    print("✨ Key Benefits:")
    print("• 🎯 Type-safe translation access")
    print("• 🌍 Multi-language support")
    print("• 📁 Organized nested namespaces")
    print("• 🔧 Parameterized translations")
    print("• 📝 Full IDE autocomplete support")
    print("• 🔍 Compile-time validation")
    print()

    print("🚀 To use in your project:")
    print("1. Add translation YAML files to i18n/")
    print("2. Configure [tool.slang] in pyproject.toml")
    print("3. Run: slang generate")
    print("4. Import and use generated translations")


if __name__ == "__main__":
    main()
